//! Turning a parsed file into symbols.

use crate::symbols::*;
use sclang_syntax::{parse, Child, SyntaxKind, SyntaxNode};
use std::path::Path;

/// Everything one file declares.
#[derive(Debug, Default)]
pub struct FileSymbols {
    pub classes: Vec<Class>,
    pub methods: Vec<Method>,
}

/// Extract the symbols declared by `source`.
///
/// Errors in the file are not a reason to produce nothing: the parser recovers,
/// so a file with a broken method still yields its other methods. That is the
/// whole point of indexing from a CST rather than from a compiler.
pub fn symbols_of(path: &Path, source: &str) -> FileSymbols {
    let parsed = parse(source);
    let mut out = FileSymbols::default();
    walk(path, source, &parsed.root, &mut out);
    out
}

/// Recursive rather than flat, so each declaration knows its parent — which is
/// where the preceding comment lives.
fn walk(path: &Path, source: &str, parent: &SyntaxNode, out: &mut FileSymbols) {
    for child in &parent.children {
        let Child::Node(node) = child else { continue };
        match node.kind {
            SyntaxKind::ClassDef => class_def(path, source, node, parent, out),
            // `+ Foo { ... }` adds methods to a class defined elsewhere, which
            // may not even be indexed yet.
            SyntaxKind::ClassExtension => {
                if let Some((name, _)) = name_token(node, source, true) {
                    methods_of(path, source, node, &name, out);
                }
            }
            _ => walk(path, source, node, out),
        }
    }
}

fn class_def(
    path: &Path,
    source: &str,
    node: &SyntaxNode,
    parent: &SyntaxNode,
    out: &mut FileSymbols,
) {
    let Some((name, name_range)) = name_token(node, source, false) else {
        return;
    };

    let superclass = node
        .child_of(SyntaxKind::SuperClass)
        .and_then(|s| {
            s.child_tokens()
                .find(|t| t.kind == SyntaxKind::ClassName)
                .map(|t| t.text(source).to_string())
        })
        // `Foo { }` with no `: Super` inherits Object; sclang resolves it that
        // way and reports `Object` for the 215 classes in the stock library
        // written like that. Leaving it implicit here stops every superclass
        // walk at such a class, which silently hides Object's methods from
        // every class beneath it.
        .or_else(|| (name != "Object").then(|| "Object".to_string()));

    let indexed_slot = node.child_of(SyntaxKind::IndexedSlot).and_then(|s| {
        s.child_tokens()
            .find(|t| t.kind == SyntaxKind::Ident)
            .map(|t| t.text(source).to_string())
    });

    let vars = vars_of(path, source, node);

    // Accessor methods generated by `<`, `>` and `<>` markers. sclang creates
    // these, so completion has to know about them.
    for v in &vars {
        let kind = match v.kind {
            VarKind::Instance => MethodKind::Instance,
            // `classvar` and `const` accessors live on the class side.
            VarKind::Class | VarKind::Const => MethodKind::Class,
        };
        if v.getter {
            out.methods.push(Method {
                name: v.name.clone(),
                owner: name.clone(),
                kind,
                args: Vec::new(),
                origin: Origin::Accessor,
                location: v.location.clone(),
                doc: None,
            });
        }
        if v.setter {
            out.methods.push(Method {
                name: format!("{}_", v.name),
                owner: name.clone(),
                kind,
                // sclang reports no argument names for generated setters.
                args: Vec::new(),
                origin: Origin::Accessor,
                location: v.location.clone(),
                doc: None,
            });
        }
    }

    out.classes.push(Class {
        name: name.clone(),
        superclass,
        indexed_slot,
        vars,
        location: Location {
            file: path.to_path_buf(),
            range: node.start..node.end,
            name_range,
        },
        doc: doc_comment(parent, source, node),
    });

    methods_of(path, source, node, &name, out);
}

fn methods_of(
    path: &Path,
    source: &str,
    class_node: &SyntaxNode,
    owner: &str,
    out: &mut FileSymbols,
) {
    for m in class_node.descendants() {
        if m.kind != SyntaxKind::MethodDef {
            continue;
        }
        let class_method = is_class_method(m);
        let Some((name, name_range)) = name_token(m, source, class_method) else {
            continue;
        };
        out.methods.push(Method {
            name,
            owner: owner.to_string(),
            kind: if class_method {
                MethodKind::Class
            } else {
                MethodKind::Instance
            },
            args: args_of(m, source),
            origin: Origin::Declared,
            location: Location {
                file: path.to_path_buf(),
                range: m.start..m.end,
                name_range,
            },
            doc: doc_comment(class_node, source, m),
        });
    }
}

fn vars_of(path: &Path, source: &str, class_node: &SyntaxNode) -> Vec<Var> {
    let mut out = Vec::new();
    for decl in class_node.descendants() {
        if decl.kind != SyntaxKind::ClassVarDecl {
            continue;
        }
        let kind = if decl
            .child_tokens()
            .any(|t| t.kind == SyntaxKind::ClassvarKw)
        {
            VarKind::Class
        } else if decl.child_tokens().any(|t| t.kind == SyntaxKind::ConstKw) {
            VarKind::Const
        } else {
            VarKind::Instance
        };

        for slot in decl.child_nodes().filter(|n| n.kind == SyntaxKind::SlotDef) {
            let Some(name_tok) = slot.child_tokens().find(|t| t.kind == SyntaxKind::Ident) else {
                continue;
            };
            let marker = slot.child_of(SyntaxKind::RwSpec).and_then(|s| {
                s.child_tokens()
                    .find(|t| !t.kind.is_trivia())
                    .map(|t| t.kind)
            });
            let (getter, setter) = match marker {
                Some(SyntaxKind::Lt) => (true, false),
                Some(SyntaxKind::Gt) => (false, true),
                Some(SyntaxKind::ReadWriteVar) => (true, true),
                _ => (false, false),
            };
            // Anything after the `=` is the default.
            let default = slot
                .children
                .iter()
                .position(|c| matches!(c, Child::Token(t) if t.kind == SyntaxKind::Eq))
                .map(|i| {
                    let start = slot.children[i + 1..]
                        .iter()
                        .find(|c| !matches!(c, Child::Token(t) if t.kind.is_trivia()))
                        .map(|c| c.range().0)
                        .unwrap_or(slot.end);
                    source[start as usize..slot.end as usize].trim().to_string()
                });

            out.push(Var {
                name: name_tok.text(source).to_string(),
                kind,
                getter,
                setter,
                default,
                location: Location {
                    file: path.to_path_buf(),
                    range: slot.start..slot.end,
                    name_range: name_tok.start..name_tok.end,
                },
            });
        }
    }
    out
}

/// Declared arguments, in order, with their default text.
fn args_of(method: &SyntaxNode, source: &str) -> Vec<Arg> {
    // Direct child only: a nested closure's arguments are not the method's.
    let Some(decls) = method.child_of(SyntaxKind::ArgDecls) else {
        return Vec::new();
    };
    decls
        .child_nodes()
        .filter(|n| matches!(n.kind, SyntaxKind::VarDef | SyntaxKind::RestArg))
        .filter_map(|n| {
            let name = n.child_tokens().find(|t| t.kind == SyntaxKind::Ident)?;
            let default = n
                .children
                .iter()
                .position(|c| matches!(c, Child::Token(t) if t.kind == SyntaxKind::Eq))
                .map(|i| {
                    let start = n.children[i + 1..]
                        .iter()
                        .find(|c| !matches!(c, Child::Token(t) if t.kind.is_trivia()))
                        .map(|c| c.range().0)
                        .unwrap_or(n.end);
                    source[start as usize..n.end as usize].trim().to_string()
                })
                .or_else(|| {
                    // The `=` is optional: `|range -1|` and `overwrite(true)`.
                    let after_name = n
                        .children
                        .iter()
                        .position(|c| matches!(c, Child::Token(t) if t.start == name.start))?;
                    let rest = n.children[after_name + 1..]
                        .iter()
                        .find(|c| !matches!(c, Child::Token(t) if t.kind.is_trivia()))?;
                    Some(
                        source[rest.range().0 as usize..n.end as usize]
                            .trim()
                            .to_string(),
                    )
                });
            Some(Arg {
                name: name.text(source).to_string(),
                default,
                is_rest: n.kind == SyntaxKind::RestArg,
            })
        })
        .collect()
}

/// The identifying token of a node, with its range.
///
/// `skip_lead` drops one leading marker — the `*` of a class method or the `+`
/// of a class extension.
fn name_token(
    node: &SyntaxNode,
    source: &str,
    skip_lead: bool,
) -> Option<(String, std::ops::Range<u32>)> {
    let mut skipped = false;
    for child in &node.children {
        if let Child::Token(t) = child {
            if t.kind.is_trivia() {
                continue;
            }
            if skip_lead && !skipped && matches!(t.kind, SyntaxKind::Star | SyntaxKind::Plus) {
                skipped = true;
                continue;
            }
            return Some((t.text(source).to_string(), t.start..t.end));
        }
    }
    None
}

/// A leading `*` is the class-method marker only when a name follows it;
/// `* { ... }` is an instance method named `*`.
fn is_class_method(node: &SyntaxNode) -> bool {
    let toks: Vec<_> = node
        .child_tokens()
        .filter(|t| !t.kind.is_trivia())
        .collect();
    matches!(toks.first(), Some(t) if t.kind == SyntaxKind::Star)
        && matches!(toks.get(1), Some(t) if t.kind != SyntaxKind::LBrace)
}

/// The run of `//` comments immediately above `node` within `parent`.
///
/// SCDoc lives in separate `.schelp` files, but a leading comment is the most
/// useful thing to show on hover for code that has no help file.
fn doc_comment(parent: &SyntaxNode, source: &str, node: &SyntaxNode) -> Option<String> {
    let idx = parent.children.iter().position(|c| match c {
        Child::Node(n) => std::ptr::eq(n, node),
        _ => false,
    })?;

    let mut lines: Vec<&str> = Vec::new();
    let mut blank_runs = 0;
    for child in parent.children[..idx].iter().rev() {
        match child {
            Child::Token(t) if t.kind == SyntaxKind::LineComment => {
                lines.push(t.text(source).trim_start_matches('/').trim());
                blank_runs = 0;
            }
            Child::Token(t) if t.kind == SyntaxKind::Whitespace => {
                // One newline keeps the run going; a blank line ends it.
                if t.text(source).matches('\n').count() > 1 {
                    break;
                }
                blank_runs += 1;
                if blank_runs > 1 {
                    break;
                }
            }
            _ => break,
        }
    }
    if lines.is_empty() {
        return None;
    }
    lines.reverse();
    Some(lines.join("\n"))
}
