//! The symbol types the index stores.

use std::ops::Range;
use std::path::PathBuf;

/// Where a symbol is written down. Byte offsets into the file's source.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Location {
    pub file: PathBuf,
    /// The whole declaration — a class body, a method definition.
    pub range: Range<u32>,
    /// Just the name. This is what goto-definition should select, and what a
    /// rename would rewrite.
    pub name_range: Range<u32>,
}

/// Instance side or class side.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum MethodKind {
    Instance,
    Class,
}

impl MethodKind {
    /// The character sclang's own reflection uses, and the one the oracle
    /// compares against.
    pub fn as_char(self) -> char {
        match self {
            MethodKind::Instance => 'i',
            MethodKind::Class => 'c',
        }
    }
}

/// How a method came to exist.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Origin {
    /// Written out as a method definition.
    Declared,
    /// Generated by sclang from a `<`, `>` or `<>` marker on a variable
    /// declaration. These are real methods — completion must offer them — but
    /// they have no definition of their own, so their location points at the
    /// variable that produced them.
    Accessor,
}

/// One declared argument.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Arg {
    pub name: String,
    /// Source text of the default, if any: `0.5`, `(2)`, `-90`.
    pub default: Option<String>,
    /// True for the trailing `...rest` parameter.
    pub is_rest: bool,
}

/// A method, on either side of a class.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Method {
    pub name: String,
    pub owner: String,
    pub kind: MethodKind,
    pub args: Vec<Arg>,
    pub origin: Origin,
    pub location: Location,
    /// The comment immediately above the definition, if there is one. SCDoc
    /// lives in separate `.schelp` files, but a leading `//` is still the most
    /// useful thing to show on hover for code that has no help file.
    pub doc: Option<String>,
}

impl Method {
    /// A signature suitable for hover or completion detail:
    /// `*new(server, startBus = 0)`.
    pub fn signature(&self) -> String {
        let mut s = String::new();
        if self.kind == MethodKind::Class {
            s.push('*');
        }
        s.push_str(&self.name);
        s.push('(');
        for (i, a) in self.args.iter().enumerate() {
            if i > 0 {
                s.push_str(", ");
            }
            if a.is_rest {
                s.push_str("...");
            }
            s.push_str(&a.name);
            if let Some(d) = &a.default {
                s.push_str(" = ");
                s.push_str(d);
            }
        }
        s.push(')');
        s
    }
}

/// An instance variable, class variable, or constant.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum VarKind {
    Instance,
    Class,
    Const,
}

/// A declared variable, with the accessor markers written on it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Var {
    pub name: String,
    pub kind: VarKind,
    /// `<` — a getter is generated.
    pub getter: bool,
    /// `>` — a setter is generated.
    pub setter: bool,
    pub default: Option<String>,
    pub location: Location,
}

/// A class, with everything declared directly on it.
///
/// Methods added by `+ Foo { ... }` extensions elsewhere are folded in, since
/// that is how sclang presents them.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Class {
    pub name: String,
    /// `None` only for `Object`, which is the one real root. A class written
    /// without `: Super` is recorded as inheriting `Object`, because that is
    /// what sclang resolves it to.
    pub superclass: Option<String>,
    /// The `[slot]` of an indexed class definition, e.g. `Array[slot]`.
    pub indexed_slot: Option<String>,
    pub vars: Vec<Var>,
    pub location: Location,
    pub doc: Option<String>,
}
